
export const actionTypes = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT: 'LOGOUT',

    ADDGROUP_REQUEST: 'ADDGROUP_REQUEST',
    ADDGROUP_SUCCESS: 'ADDGROUP_SUCCESS',
    ADDGROUP_FAILURE: 'ADDGROUP_FAILURE',

    DELETEGROUP_REQUEST: 'DELETEGROUP_REQUEST',
    DELETEGROUP_SUCCESS: 'DELETEGROUP_SUCCESS',
    DELETEGROUP_FAILURE: 'DELETEGROUP_FAILURE',

    // ADD_USER: 'ADD_USER',
    // UPDATE_USER: 'UPDATE_USER',
    // UPDATE_PROFILE_PICTURE: 'UPDATE_PROFILE_PICTURE',
    // FORM_SUBMITION_STATUS: 'FORM_SUBMITION_STATUS'
}
