
export const actionTypes = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT: 'LOGOUT',

    // ADD_USER: 'ADD_USER',
    // UPDATE_USER: 'UPDATE_USER',
    // UPDATE_PROFILE_PICTURE: 'UPDATE_PROFILE_PICTURE',
    // FORM_SUBMITION_STATUS: 'FORM_SUBMITION_STATUS'
}
